name: 游 Bug report
labels: [Bug, Triage]
title: "[Bug]: "
description: Describ칤 el error/bug encontrado.
body:
  - type: markdown
    attributes:
      value: Desde ya, gracias por tomarte el tiempo para completar esta solicitud. Nos gustar칤a mucho que vos trabajes en tu bug!

  - type: textarea
    id: bug-report
    attributes:
      label: 쮺u치l es el bug/error que has encontrado?
      description: Describe el error que has encontrado.
    validations:
      required: true

  - type: textarea
    id: bug-expected-behavior
    attributes:
      label: 쮺u치l es el comportamiento esperado?
      description: 쯈u칠 deber칤a suceder?
    validations:
      required: true

  - type: textarea
    id: bug-fix-suggested
    attributes:
      label: Si tienes una soluci칩n, 쯖u치les son los pasos necesarios para implementarla?
      description: Describe la soluci칩n propuesta.

  - type: textarea
    id: bug-replicate
    attributes:
      label: 쮺칩mo se puede reproducir este error?
      description: Indica los pasos necesarios para que el error sea reproducido por otras personas.
      placeholder: |
        1. Ejecutar 'yarn dev'...
        2. Ir al la direcci칩n...
        3. Hacer click en bot칩n...
        4. Ver el error en consola...
    validations:
      required: true

  - type: dropdown
    id: bug-browsers
    attributes:
      label: 쮺u치l es el navegador en el que sucede el error?
      multiple: true
      options:
        - No aplica
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Otro navegador
        - Todos los anteriores
    validations:
      required: true

  - type: input
    id: bug-another-browser
    attributes:
      label: Otro navegador que est칠s utilizando.
      description: En el caso de que hayas seleccionado "Otro navegador", te pedimos que coloques su nombre ac치.
      placeholder: Brave

  - type: textarea
    id: bug-logs
    attributes:
      label: Por favor complet치 con logs relevantes respecto al bug.
      description: Si es posible, indica el mensaje de error arrojado por el navegador.

  - type: checkboxes
    id: bug-agreement
    attributes:
      label: C칩digo de conducta y licencia.
      options:
        - label: He comprobado que no se haya reportado el issue.
          required: true
        - label: Estoy de acuerdo con seguir el [c칩digo de conducta](https://github.com/Juguetear/juguetear-web/blob/development/CODE_OF_CONDUCT.md) de este proyecto.
          required: true
        - label: Estoy de acuerdo con seguir las [licencias](https://github.com/Juguetear/juguetear-web/blob/development/CONTRIBUTING.md#licencias) de este proyecto.
          required: true
