name: 游 Bug report
labels: [Bug, Triage]
title: "[Bug]: "
description: Describ칤 el error/bug encontrado.
body:
  - type: markdown
    attributes:
      value: |
        Desde ya gracias por tomarte el tiempo para completar esta solicitud, tambi칠n nos gustar칤a mucho que trabajes en tu bug!

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: C칩digo de conducta.
      description: Al completar esta solicitud, acept치s el [C칩digo de Conducta](https://github.com/Juguetear/juguetear-web/CODE_OF_CONDUCT.md)
      options:
        - label: Estoy de acuerdo con seguir el C칩digo de Conducta de este proyecto.
          required: true
  - type: checkboxes
    id: licence
    attributes:
      label: Licencia.
      description: Al completar esta solicitud, acept치s las [licencias del repositorio](https://github.com/Juguetear/juguetear-web/blob/development/CONTRIBUTE.md#licencias)
      options:
        - label: Estoy de acuerdo con seguir las licencias de este proyecto.
          required: true
  - type: checkboxes
    id: feat-check
    attributes:
      label: He comprobado que no se haya reportado el issue.
      description: Has comprobado que el issue no haya sido reportado previamente.
      options:
        - label: He verificado que el issue no haya sido reportado previamente.
          required: true

  - type: textarea
    id: bug
    attributes:
      label: 쮺u치l es el bug/error que has encontrado?
      description: Describe el error que has encontrado.
    validations:
      required: true

  - type: textarea
    id: replicate-bug
    attributes:
      label: 쮺칩mo se puede reproducir este error?
      description: Indica los pasos necesarios para que el error sea reproducido por otras personas.
      placeholder: "
        1. Clickear en boton..
        2.
        3.
        "
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 쮺u치l es el comportamiento esperado?
      description: 쯈u칠 deber칤a suceder?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: 쮺u치l es el comportamiento actual?
      description: Describe el comportamiento actual.
    validations:
      required: true

  - type: textarea
    id: suggested-fix
    attributes:
      label: Si tienes una soluci칩n, 쯖u치les son los pasos necesarios para implementarla?
      description: Describe la soluci칩n propuesta.

  - type: dropdown
    id: browsers
    attributes:
      label: 쮺u치l es el navegador en el que sucede el error?
      multiple: true
      options:
        - No aplica
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Otro navegador
    validations:
      required: true

  - type: input
    id: another-browser
    attributes:
      label: Otro navegador que est칠s utilizando.
      description: En el caso de que hayas seleccionado "Otro navegador", te pedimos que coloques su nombre ac치.
      placeholder: Brave

  - type: textarea
    id: log
    attributes:
      label: Por favor complet치 con logs relevantes respecto al bug.
      description: Si es posible, indica el mensaje de error arrojado por el navegador.
